## Bind key: reload, split
bind r source-file ~/.tmux.conf # \\; display "Reloaded!"
#bind | split-window -h
#bind - split-window -v


## Bind key: select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind m last-window

## Resize: usage "ctrl + b + (Alt) + arrow"
#bind -r H resize-pane -L 5
#bind -r J resize-pane -D 5
#bind -r K resize-pane -U 5
#bind -r L resize-pane -R 5

## Mouse functionalities
#setw -g mouse on
#bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
#bind -n WheelDownPane select-pane -t= \;                 send-keys -M

set -g mode-mouse on 
set -g mouse-resize-pane on 
set -g mouse-select-pane on 
set -g mouse-select-window on

#bind -t vi-copy    C-WheelUpPane   halfpage-up
#bind -t vi-copy    C-WheelDownPane halfpage-down
#bind -t emacs-copy C-WheelUpPane   halfpage-up
#bind -t emacs-copy C-WheelDownPane halfpage-down


## Settings
setw -g mode-keys vi # vim key
set -g default-terminal "screen-256color" # terminal color
setw -g xterm-keys on # xterm key

## Color (Solarized 256)
# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default
# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim
# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright
# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01
# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange
# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour colour64 #green
