## Bind key: reload, split
bind r source-file ~/.tmux.conf # \\; display "Reloaded!"
#bind | split-window -h
#bind - split-window -v

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

## Bind key: select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind m last-window

## Resize: usage "ctrl + b + (Alt) + arrow"
#bind -r H resize-pane -L 5
#bind -r J resize-pane -D 5
#bind -r K resize-pane -U 5
#bind -r L resize-pane -R 5

## Mouse functionalities (tmux 2.5)
setw -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

## Settings
setw -g mode-keys vi # vim key
set -g default-terminal "screen-256color" # terminal color
setw -g xterm-keys on # xterm key
set-option -g allow-rename off

## Color (Solarized 256)
# default statusbar colors
set-option -g status-style bg=colour235,fg=colour136,default
# default window title colors
set-window-option -g window-status-style bg=default,fg=colour244,dim
# active window title colors
set-window-option -g window-status-current-style bg=default,fg=colour166,bright
# pane border
set-option -g pane-border-style fg=colour235
set-option -g pane-active-border-style fg=colour240
# message text
set-option -g message-style bg=colour235,fg=colour166
# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour colour64 #green
