#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LANG='ko_KR.UTF-8'
export LC_ALL='ko_KR.UTF-8'
export PAGER='less'
export EDITOR='vim'
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

alias tmux='tmux -2'
alias cd='cdls'
