#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LANG='ko_KR.UTF-8'
export LC_ALL='ko_KR.UTF-8'
export PAGER='less'
export EDITOR='vim'
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

export PATH=/usr/local/libexec/ccache:$PATH
export CCACHE_PATH=/usr/bin:/usr/local/bin
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_LOGFILE=/var/log/ccache.log
#export CCACHE_PREFIX="distcc"

export JAVA_VERSION="1.8"
export JAVA_OS="native"
export PATH=${JAVA_HOME}/bin:${PATH}
export SWT_GTK3=0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/system/lib:/usr/local/lib

alias tmux='tmux -2'
alias cd='cdls'
alias cdt='cd ~/browser/src'
alias cdd='cd /usr/local/togate/Debug'
alias cdk='cd /root/trunk/src'
